version: '3'
services: 
  ide:
    build: .
    volumes:
    - idedata:/ide/src/spring
    - mdbdata:/ide/mdb/data:ro
    # - faasdata:/faas
    ports: 
    - "55017:3000"
    restart: always
    networks: 
      bfast_net:
        ipv4_address: 172.28.1.1
  web:
    build: ./services/webRuntime/
    ports: 
    - "6000:80"
    # - "443:443"
    restart: always
    # volumes: 
    #   - webdata:'/'
    networks: 
      bfast_net:
        ipv4_address: 172.28.1.2
  mdb:
    image: mongo
    volumes:
    - mdbdata:/var/data
    restart: always
    networks: 
      bfast_net:
        ipv4_address: 172.28.1.3
  daas:
    build: ./services/daasRuntime
    restart: always
    volumes:
    - daasdata:/app
    - idedata:/ide:ro
    # links: 
    #   - ide
    #   - mdb
    networks: 
      bfast_net:
        ipv4_address: 172.28.1.4
  # faas:
  #   image: ubuntu:bionic
  #   restart: always
  #   volumes: 
  #   - faasdata:/faas
volumes: 
  idedata: {}
  mdbdata: {}
  daasdata: {}
  faasdata: {}
  webdata: {}
networks: 
  bfast_net:
    ipam: 
      driver: default
      config: 
        - subnet: 172.28.0.0/16
  
